services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: intradyne
      POSTGRES_PASSWORD: intradyne
      POSTGRES_DB: intradyne
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U intradyne"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: "@Dockerfile"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DB_URL: postgresql://intradyne:intradyne@postgres:5432/intradyne
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/readyz').read(); print('ok')"]
      interval: 10s
      timeout: 3s
      retries: 5
    command: ["uvicorn", "intradyne.api.app:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  pgdata: {}
