
services:
  api:
    build:
      context: ..
      dockerfile: Dockerfile
    image: intradyne-lite:1.9.0
    env_file:
      - ../.env
    environment:
      - PYTHONPATH=/app/src
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - RATE_LIMIT_REQS=${RATE_LIMIT_REQS:-120}
      - RATE_LIMIT_WINDOW=${RATE_LIMIT_WINDOW:-60}
    command: uvicorn intradyne.api.app:app --host 0.0.0.0 --port 8000
    volumes:
      - ../data:/app/data
      - ../reports:/app/reports
    read_only: true
    tmpfs:
      - /tmp
    mem_limit: 512m
    cpus: 0.50
    restart: unless-stopped
    networks: [web]

  caddy:
    image: caddy:2
    restart: unless-stopped
    environment:
      - ACME_AGREE=true
      - CADDY_EMAIL=${CADDY_EMAIL}
      - DOMAIN=${DOMAIN}
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    networks: [web]

networks:
  web: {}

volumes:
  caddy_data: {}
  caddy_config: {}
