services:
  api:
    build:
      context: ..
      dockerfile: Dockerfile
    image: intradyne-lite:1.9.0
    env_file:
      - ../.env
    environment:
      - PYTHONPATH=/app/src
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    command: uvicorn intradyne.api.app:app --host 0.0.0.0 --port 8000
    volumes:
      - ../data:/app/data
      - ../reports:/app/reports
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    networks: [edge]

  nginx:
    image: nginx:1.27-alpine
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api
    networks: [edge]

networks:
  edge: {}

