version: "3.9"
services:
  engine:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: intradyne-engine
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      - TZ=Asia/Kuching
    volumes:
      - ../reports:/app/reports
      - ../data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
