name: CI

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest mypy ruff

      - name: Ruff (lint)
        run: |
          ruff --version
          ruff check src

      - name: Mypy (type check)
        run: |
          mypy --version
          mypy src

      - name: Pytest (unit tests)
        run: |
          python -m pytest -q @tests

      - name: Docker build
        run: |
          docker --version
          docker build -f @Dockerfile -t intradyne-lite:ci .

